---
- hosts: localhost
  become: yes
  tasks:
    - name: Install vim
      dnf: name=vim-enhanced state=latest
    - name: Install bat
      dnf: name=bat state=latest
    - name: Install and configure snapd on Fedora
      when: ansible_facts['os_family'] == "RedHat"
      block:
        - name: Install snapd
          dnf: 
            name: snapd 
            state: latest
        - name: Create link for snapd to work
          file: 
            src: /var/lib/snapd/snap
            dest: /snap
            state: link
    - name: Install VS Code
      snap:
        name: code
        state: present
        classic: yes
#   - name: Install RPMFusion repo
#     dnf: name=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm
#     dnf: name=https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm
